### ISSUE TITLE
You should use Firebase Hosting instead of Github Pages for security

### ISSUE THREAD

**Issue by K1ngjulien** [CodingTrain/CrowdSourceColorData#1]
Hi!

The way your project is setup now you are exposing all your credentials which is really bad!

You should use Firebase Hosting instead because it does not require that you put your credentials in the code!
Also it is really easy using the CLI:
https://firebase.google.com/docs/hosting/quickstart

**Comment by Tensorr** [comment]
or put the keys in a separate .js and .gitignore it

**Comment by emielhman** [comment]
Maybe add the ip address of the client to each row in the database?

You can easily retrieve the ip address of the client with this piece of code: 

```
$.getJSON('https://json.geoiplookup.io/api?callback=?', function(data) {
  console.log(data["ip"]);
});
```

That way you can limit every client to a limited amount of entries, a 1000 entries for example.

Because right now you're able to simply spam the database with trash by simply copy pasting the code below, into the chrome console window. Which is probably not something we want.. 
(And I personally think learning how to securely retrieve data through a public form like this is a very vital part of the process! 👍 )

```
function foo() {
    sendData();
    setTimeout(foo, 1000);
}

function sendData() {
  let colorDatabase = database.ref('colors');
	
	let arr = ["red-ish", "green-ish", "blue-ish", "orange-ish", "yellow-ish", "pink-ish", "purple-ish", "brown-ish", "grey-ish"];
  // Make an object with data in it
  var data = {
    r: r,
    g: g,
    b: b,
    label: arr[Math.floor(Math.random() * arr.length)]
  }
for(let i = 0; i < 100; i++){
  let color = colorDatabase.push(data, finished);
}
  // Reload the data for the page
  function finished(err) {
    if (err) {
      console.error("ooops, something went wrong.");
      console.error(err);
    } else {
      console.log('Data saved successfully');
      pickColor();
    }
  }
}

function foo() {

    // your function code here
	sendData();
    setTimeout(foo, 1000);
}

foo();
```

In any case I really enjoyed the livestream!
It was fun to get a 'behind-the-scenes'-look of how the videos get made!

**Comment by meiamsome** [comment]
The `apiKey` of Firebase is not a secret and can be given out publicly. The security model of Firebase Realtime Database relies on the `rules` being correctly setup as they were shown in the livestream.

I can see no reference to Firebase hosting providing the API keys in a different manner, you have to include the library and keys yourself as you would with any other platform, although if you have a link to the reference documentation that shows this to be false I would be interested in hearing it.

@emielhman Yeah, that might work but that's entirely client side, there's nothing to stop someone just doing `setInterval(() => firebase.database().ref(...).push(garbage))` where garbage has a 'random' IP. Besides, Firebase supports something that tries to do something like this anyway: https://firebase.google.com/docs/auth/web/anonymous-auth

**Comment by K1ngjulien** [comment]
when you set up the firebase hosting with `firebase init` it generates a template project without any api keys anywhere which relys on being hosted on firebase.


This is the sample page that gets generated which you can immediatly deploy and use without adding anything

html```

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Welcome to Firebase Hosting</title>

    
    <script defer src="/__/firebase/5.0.4/firebase-app.js"></script>
    
    <script defer src="/__/firebase/5.0.4/firebase-auth.js"></script>
    <script defer src="/__/firebase/5.0.4/firebase-firestore.js"></script>
    <script defer src="/__/firebase/5.0.4/firebase-messaging.js"></script>
    <script defer src="/__/firebase/5.0.4/firebase-storage.js"></script>
    
    <script defer src="/__/firebase/init.js"></script>

    <style media="screen">
      body { background: #ECEFF1; color: rgba(0,0,0,0.87); font-family: Roboto, Helvetica, Arial, sans-serif; margin: 0; padding: 0; }
      #message { background: white; max-width: 360px; margin: 100px auto 16px; padding: 32px 24px; border-radius: 3px; }
      #message h2 { color: #ffa100; font-weight: bold; font-size: 16px; margin: 0 0 8px; }
      #message h1 { font-size: 22px; font-weight: 300; color: rgba(0,0,0,0.6); margin: 0 0 16px;}
      #message p { line-height: 140%; margin: 16px 0 24px; font-size: 14px; }
      #message a { display: block; text-align: center; background: #039be5; text-transform: uppercase; text-decoration: none; color: white; padding: 16px; border-radius: 4px; }
      #message, #message a { box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24); }
      #load { color: rgba(0,0,0,0.4); text-align: center; font-size: 13px; }
      @media (max-width: 600px) {
        body, #message { margin-top: 0; background: white; box-shadow: none; }
        body { border-top: 16px solid #ffa100; }
      }
    </style>
  </head>
  <body>
    <div id="message">
      <h2>Welcome</h2>
      <h1>Firebase Hosting Setup Complete</h1>
      <p>You're seeing this because you've successfully setup Firebase Hosting. Now it's time to go build something extraordinary!</p>
      <a onclick="loadData()">Load Data</a>
    </div>
    <p id="load">Firebase SDK Loading&hellip;</p>

    <script>
      document.addEventListener('DOMContentLoaded', function() {
        // // 🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥
        // // The Firebase SDK is initialized and available here!
        //
        // firebase.auth().onAuthStateChanged(user => { });
        // firebase.database().ref('/path/to/ref').on('value', snapshot => { });
        // firebase.messaging().requestPermission().then(() => { });
        // firebase.storage().ref('/path/to/ref').getDownloadURL().then(() => { });
        //
        // // 🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥

        try {
          let app = firebase.app();
          let features = ['auth', 'database', 'messaging', 'storage'].filter(feature => typeof app[feature] === 'function');
          document.getElementById('load').innerHTML = `Firebase SDK loaded with ${features.join(', ')}`;
        } catch (e) {
          console.error(e);
          document.getElementById('load').innerHTML = 'Error loading the Firebase SDK, check the console.';
        }
      });
      
      
      function loadData() {
        console.log(firebase.firestore().collection("cities").doc());
      }
    </script>
  </body>
</html>

```

**Comment by meiamsome** [comment]
Ah, ok, so it just auto-hosts the keys at `/__/firebase/init.js` then - see https://firestarter-96e46.firebaseapp.com/__/firebase/init.js for example :)

**Comment by K1ngjulien** [comment]
yes I believe that is the case

**Comment by mattvick** [comment]
This [Stack Exchange answer](https://stackoverflow.com/questions/37482366/is-it-safe-to-expose-firebase-apikey-to-the-public#answer-37484053) might help visitors better understand this issue.
