### ISSUE TITLE
Removing data with invalid labels

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/CrowdSourceColorData#15]
More related to #14 from @panzer, I would love to have some functionality to remove data with invalid labels, i.e. if there is something in the database with a label that doesn't match one of the buttons, remove it.

**Comment by Versatilus** [comment]
I think this is another great opportunity to emphasize the role of data preparation. It's more than just collecting data. It's important to clean it and make sure it's appropriate to your task.

**Comment by shiffman** [comment]
@meiamsome has helped me rewrite the rules to protect against invalid entries. Yay!

```json
{ 
    "rules": {
    ".read": "false",
    ".write": "false",
    "colorData": {
      "$entry": {
        ".write": "!data.exists()",
        "r": {
          ".validate": "newData.isNumber() && newData.val() >= 0 && newData.val() <= 255"
        },
        "g": {
          ".validate": "newData.isNumber() && newData.val() >= 0 && newData.val() <= 255"
        },
        "b": {
          ".validate": "newData.isNumber() && newData.val() >= 0 && newData.val() <= 255"
        },
        "label": {
          ".validate": "newData.isString() && newData.val().matches(/^(red|green|blue|orange|yellow|pink|purple|brown|grey)-ish$/)"
        },
        "$otherKey": {
          ".validate": "false",
        },
        ".validate": "newData.hasChildren(['r', 'g', 'b', 'label'])"
      }
    }
  }
}
```

There's an easter egg in the above for anyone who cares to notice.

**Comment by shiffman** [comment]
This is now all set with the new rules.
