### ISSUE TITLE
read access to data potentially revoked?

### ISSUE THREAD

**Issue by panzer** [CodingTrain/CrowdSourceColorData#18]
When running
`database.ref("colors").once("value").then(result => console.log(result))`

Firebase throws
<img width="569" alt="screen shot 2018-06-14 at 11 02 16 am" src="https://user-images.githubusercontent.com/3926534/41420509-9bbfcaae-6fc2-11e8-970f-19f07498ff29.png">

This means the most important part of #9 (retrieving data) is broken. :(
Did something change in the Firebase settings?

**Comment by panzer** [comment]
I suspect this has to do with #16. I'll attempt a quick fix before your livestream starts...

**Comment by shiffman** [comment]
Yes, I just turned "read" back on, let me know if it works.

**Comment by panzer** [comment]
Thanks! That worked.

However, I am now getting only a few thousand entries in the database whereas last night I was seeing hundreds of thousands. The data I'm receiving with `loadData()` looks mostly clean. Maybe you cleared the database? Maybe some other database setting?

The good news is that the data looks good now, even without any of my methods!

**Comment by shiffman** [comment]
haha, yeah, i wiped the database after @meiamsome helped me add new rules. sad to lose the data from last night, but live and learn!
